//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoranBilal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int id { get; set; }
        public Nullable<int> tableID { get; set; }
        public Nullable<System.DateTime> reservationTime { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> clientID { get; set; }
        public Nullable<System.DateTime> checkout { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Table Table { get; set; }
    }
}
