//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoranBilal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialProduct
    {
        public int id { get; set; }
        public string header { get; set; }
        public string photo { get; set; }
        public string description { get; set; }
        public string btnText { get; set; }
        public Nullable<int> discount { get; set; }
        public Nullable<System.DateTime> distartDate { get; set; }
        public Nullable<System.DateTime> experienceDate { get; set; }
    }
}
